<?php

/*
 * Implements hook_menu()
 */

function adinsight_menu() {
  $items = array();

  $items['admin/config/services/adinsight'] = array(
      'title' => 'AdInsight',
      'description' => 'Configure the AdInsight field formatter.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('adinsight_admin'),
      'access callback' => TRUE,
      'file' => 'adinsight.admin.inc',
      'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_init()
 */
function adinsight_init() {
  
  $path_is_admin = path_is_admin(current_path());
  $adinsightid = variable_get('adinsight_id', NULL);
  
  //We don't need the script on the admin pages - so check if the user is on an 
  //admin page, and then return nothing if they are
 
  if (is_null($adinsightid) && $path_is_admin == TRUE) {
    $link = l('here', 'admin/config/services/adinsight');
    drupal_set_message(t('You haven\'t set your AdInsight ID yet. You can do it !here.', array('!here' => $link)));
  }
  //Only add the scripts if the AdInsight ID is set
  if (!is_null($adinsightid) && $path_is_admin == FALSE) {
    $settings = array();

    $settings['adinsight'] = array(
        'id' => $adinsightid,
    );
   
    drupal_add_js($settings, array('type' => 'setting'));
    drupal_add_js(drupal_get_path('module', 'adinsight') . '/adinsight.js', array('type' => 'file', 'scope' => 'header', 'weight' => 5));
  } 
}

/**
 * Implements hook_field_formatter_info()
 */
function adinsight_field_formatter_info() {
  return array(
      'adinsight_phone_formatter' => array (
      'label' => t('AdInsight Number'),
      'field types' => 'text',
      'settings' => array(
          'fallback_phone' => NULL,
      ),
      ),
  );
}

/*
 * Implements hook_field_formatter_settings_form()
 */

function adinsight_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  //This gets the view_mode where our settings are stored
  $display = $instance['display'][$view_mode];
  //Get the current settings
  $settings = $display['settings'];
  //Initialize the element variable
  $element = array();
  
  $element['fallback_phone'] = array(
      '#type' => 'textfield',
      '#title' => t('Fallback phone number'),
      '#default_value' => $settings['default_phone'],
      '#description' => t('Enter the fallback phone number for this field in case JavaScript is disabled or AdInsight cannot be reached.'),
  );
}