<?php

/*
 * Implements hook_menu()
 */

function adinsight_menu() {
  $items = array();

  $items['admin/config/services/adinsight'] = array(
      'title' => 'AdInsight',
      'description' => 'Configure the AdInsight field formatter.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('adinsight_admin'),
      'access callback' => TRUE,
      'file' => 'adinsight.admin.inc',
      'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_enable();
 */
function adinsight_enable() {
  $link = l(t('here'), 'admin/config/services/adinsight');
  $text = t('Don\'t forget to go and set your AdInsight ID !link.', array('!link' => $link));

  drupal_set_message($text, 'status');
}

/**
 * Implements hook_init()
 */
function adinsight_init() {
  $adinsightid = variable_get('adinsight_id', NULL);

  if (!is_null($adinsightid)) {
    $settings = array();

    $settings['adinsight'] = array(
        'id' => $adinsightid,
    );
   
    drupal_add_js($settings, array('type' => 'setting'));
    drupal_add_js(drupal_get_path('module', 'adinsight') . '/adinsight.js', array('type' => 'file', 'scope' => 'header', 'weight' => 5));

  }
}